=== MerapiPanel/MerapiPanel/schema/theme.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Theme",
    "type": "object",
    "properties": {
        "name": {
            "type": "string"
        },
        "author": {
            "type": "string"
        },
        "author-url": {
            "type": "string"
        },
        "description": {
            "type": "string"
        },
        "license": {
            "type": "string"
        },
        "website": {
            "type": "string"
        }
    },
    "required": [
        "name",
        "author",
        "description",
        "license"
    ]
}

=== MerapiPanel/MerapiPanel/test.json
{
    "$schema": "https://raw.githubusercontent.com/MerapiPanel/MerapiPanel/main/schema/theme.json",
    "author": "il4mb",
    "author-url": "https://github.com/il4mb",
    "description": "MerapiPanel",
    "license": "MIT",
    "name": "MerapiPanel",
    "website": "https://github.com/MerapiPanel/MerapiPanel"
}
